'use client';
import { useState } from 'react';
import { Shield, Lock, UserPlus } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuthStore } from '@/lib/auth-store';
import { PasswordStrength } from '@/components/password-strength';

export default function AdminSecurityPage(){
 const {token}=useAuthStore(); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [loading,setLoading]=useState(false);
 const [pw,setPw]=useState({currentPassword:'',newPassword:'',confirm:''});
 const [admin,setAdmin]=useState({name:'',email:'',password:'',phone:''});
 const call=async(url:string,body:any)=>{setLoading(true);setMsg('');setErr('');try{const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json(); if(!r.ok)setErr(d.error||'حدث خطأ'); else setMsg(d.message||'تم بنجاح'); return r.ok;}finally{setLoading(false)}};
 return <div className="max-w-4xl mx-auto space-y-6"><div className="flex items-center gap-3"><div className="size-10 rounded-lg bg-emerald-100 flex items-center justify-center"><Shield className="size-5 text-emerald-700"/></div><div><h1 className="text-xl font-bold">الأمان والمدراء</h1><p className="text-sm text-muted-foreground">تغيير كلمة مرور المدير وإضافة مدير جديد</p></div></div>{msg&&<div className="p-3 rounded-lg bg-emerald-50 text-emerald-700 text-sm">{msg}</div>}{err&&<div className="p-3 rounded-lg bg-red-50 text-red-700 text-sm">{err}</div>}<div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Lock className="size-4"/>تغيير كلمة مرورك</CardTitle><CardDescription>يلزم إدخال كلمة المرور الحالية</CardDescription></CardHeader><CardContent className="space-y-3"><div><Label>كلمة المرور الحالية</Label><Input type="password" dir="ltr" value={pw.currentPassword} onChange={e=>setPw({...pw,currentPassword:e.target.value})}/></div><div><Label>كلمة المرور الجديدة</Label><Input type="password" dir="ltr" value={pw.newPassword} onChange={e=>setPw({...pw,newPassword:e.target.value})}/><PasswordStrength password={pw.newPassword}/></div><div><Label>تأكيد كلمة المرور</Label><Input type="password" dir="ltr" value={pw.confirm} onChange={e=>setPw({...pw,confirm:e.target.value})}/></div><Button disabled={loading||!pw.currentPassword||!pw.newPassword||pw.newPassword!==pw.confirm} onClick={()=>call('/api/admin/security/change-password',{currentPassword:pw.currentPassword,newPassword:pw.newPassword}).then(ok=>ok&&setPw({currentPassword:'',newPassword:'',confirm:''}))}>حفظ كلمة المرور</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><UserPlus className="size-4"/>إضافة مدير جديد</CardTitle><CardDescription>سيتم إنشاء المدير مفعلًا مباشرة بدون بريد OTP</CardDescription></CardHeader><CardContent className="space-y-3"><div><Label>الاسم</Label><Input value={admin.name} onChange={e=>setAdmin({...admin,name:e.target.value})}/></div><div><Label>البريد</Label><Input dir="ltr" value={admin.email} onChange={e=>setAdmin({...admin,email:e.target.value})}/></div><div><Label>الهاتف اختياري</Label><Input dir="ltr" value={admin.phone} onChange={e=>setAdmin({...admin,phone:e.target.value})}/></div><div><Label>كلمة المرور</Label><Input type="password" dir="ltr" value={admin.password} onChange={e=>setAdmin({...admin,password:e.target.value})}/><PasswordStrength password={admin.password}/></div><Button disabled={loading||!admin.name||!admin.email||!admin.password} onClick={()=>call('/api/admin/security/create-admin',admin).then(ok=>ok&&setAdmin({name:'',email:'',password:'',phone:''}))}>إضافة المدير</Button></CardContent></Card></div></div>
}
